Repository DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA, pull requests merged in 2023-08, with the labels that each got.

#98 chore: add icons in assets
  SickSangHae/Application/Assets.xcassets/.DS_Store
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/100.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/1024.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/114.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/120.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/144.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/152.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/167.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/180.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/20.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/29.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/40.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/50.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/57.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/58.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/60.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/72.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/76.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/80.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/87.png
  SickSangHae/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🔧 chore

#100 #59/camera&ocr navigation
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/View/CameraView.swift
  SickSangHae/View/DirectItemCheckView.swift
  SickSangHae/View/DirectUpdateItemView.swift
  SickSangHae/View/OCRItemCheckView.swift
  SickSangHae/View/OCRUpdateItemView.swift
  SickSangHae/View/Reusable/OCRView.swift
Labels: ✨ feature

#97 #66/setting view
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Global/Extensions/Gradient+Extension.swift
  SickSangHae/Info.plist
  SickSangHae/Model/NotificationManager.swift
  SickSangHae/Model/NotificationModel.swift
  SickSangHae/Model/SettingModel.swift
  SickSangHae/View/NotificationView.swift
  SickSangHae/View/SettingVIew.swift
  SickSangHae/View/SettingView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/ViewModel/NotificationViewModel.swift
  SickSangHae/ViewModel/SettingViewModel.swift
Labels: ✨ feature

#101 #12/implement history view
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/OCRUpdateItemView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/CenterAlertView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/Reusable/TopAlertView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
  SickSangHae/ViewModel/TopAlertViewModel.swift
Labels: ⚒️ fix

#106 #105/item detail view bug fix
  SickSangHae/View/ItemDetailView.swift
Labels: 🐞 bug

#103 bugfix: fix navigation bug in real iPhone
  SickSangHae/View/OCRItemCheckView.swift
Labels: 🐞 bug

#108 #104/chart view spoiled error
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/ChartView.swift
Labels: 🐞 bug

#110 #109/DirectUpdateItemView bugfix
  SickSangHae/View/DirectUpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: 🐞 bug

#112 bugfix: change datePicker height and layout
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/View/CameraView.swift
  SickSangHae/View/DirectUpdateItemView.swift
  SickSangHae/View/OCRItemCheckView.swift
  SickSangHae/View/OCRUpdateItemView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
Labels: 🐞 bug

#113 #107/OCR 과 직접추가 날짜버그 수정
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/DirectItemCheckView.swift
  SickSangHae/View/DirectUpdateItemView.swift
  SickSangHae/View/EditItemDetailView.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/OCRItemCheckView.swift
  SickSangHae/View/OCRUpdateItemView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/Reusable/SmallButtonView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: 🐞 bug

#117 chore: update README.md
  README.md
Labels: 🔧 chore

#121 #119/fix item detail view
  SickSangHae/Global/Extensions/View+Extension.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/Reusable/SmallButtonView.swift
  SickSangHae/View/Reusable/TopAlertView.swift
Labels: 🐞 bug, ✨ feature

#123 fix: design qa
  SickSangHae/View/NotificationView.swift
Labels: ⚒️ fix

#120 #118/implement search bar
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/View/MainView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
  SickSangHae/ViewModel/MainViewModel.swift
Labels: ✨ feature
