Repository DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA, pull requests merged in 2023-07, with the labels that each got.

#5 feature: create Number+Extension
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/Global/Extensions/Number+Extension.swift
  SickSangHae/View/MainView.swift
Labels: ✨ feature

#8 #6/core data model setup
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Model/ItemStatus.swift
  SickSangHae/Model/PersistentController.swift
  SickSangHae/Model/Receipt+CoreDataClass.swift
  SickSangHae/Model/Receipt+CoreDataProperties.swift
  SickSangHae/Model/SickSangHaeModel.xcdatamodeld/SickSangHaeModel.xcdatamodel/contents
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature

#9 #1/fastlane cicd
  .github/workflows/pullRequest.yml
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHaeTests/SickSangHaeTests.swift
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Scanfile
Labels: ✨ feature

#20 #14/tab bar view
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/Assets.xcassets/PrimaryB.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/PrimaryG.colorset/Contents.json
  SickSangHae/View/TabBarView.swift
  SickSangHae/View/UpdateItemView.swift
Labels: ✨ feature

#24 #14/LongTermList
  SickSangHae/Application/Assets.xcassets/Gray600.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/Gray900.colorset/Contents.json
  SickSangHae/View/Reusable/LongTermList.swift
Labels: ✨ feature

#27 #14/LongTermList-2
  SickSangHae/View/Reusable/LongTermList.swift
Labels: ⚒️ fix

#26 #14/basic list
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/Reusable/BasicList.swift
Labels: ✨ feature

#30 #14/BasicList-2
  SickSangHae/View/Reusable/BasicList.swift
Labels: ⚒️ fix

#32 #14/basic list-3
  SickSangHae/Application/Assets.xcassets/Gray50.colorset/Contents.json
  SickSangHae/View/Reusable/BasicList.swift
Labels: ⚒️ fix

#33 #14/LongTermList-3 Design 수정
  SickSangHae/View/Reusable/LongTermList.swift
Labels: ⚒️ fix

#21 #7/camera custom
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/Assets.xcassets/ic_gallery.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/ic_gallery.imageset/ic_gallery.svg
  SickSangHae/Application/Assets.xcassets/ic_gallery.svg
  SickSangHae/Application/Assets.xcassets/img_cameraShutter.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/img_cameraShutter.imageset/img_cameraShutter.svg
  SickSangHae/Application/Assets.xcassets/img_cameraShutter.svg
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/Global/Extensions/ImagePicker+Extension.swift
  SickSangHae/Model/CameraModel.swift
  SickSangHae/View/CameraView.swift
  SickSangHae/ViewModel/CameraViewModel.swift
Labels: ✨ feature

#34 #14/implement main view
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/Assets.xcassets/Gray100.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/Gray200.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/Gray50.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/Gray600.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/Gray900.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/PrimaryB.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/PrimaryG.colorset/Contents.json
  SickSangHae/Application/Assets.xcassets/PrimaryGB.colorset/Contents.json
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/TabBarView.swift
Labels: ✨ feature

#43 #28/coredata crud
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/Model/Categories.swift
  SickSangHae/Model/ItemStatus.swift
  SickSangHae/Model/PersistentController.swift
  SickSangHae/Model/Receipt+CoreDataProperties.swift
  SickSangHae/Model/SickSangHaeModel.xcdatamodeld/SickSangHaeModel.xcdatamodel/contents
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature

#47 #14/fix main view ui
  SickSangHae/View/MainView.swift
Labels: ⚒️ fix

#45 #12/implement history view
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/View/HistoryView.swift
Labels: ✨ feature

#48 #14/fix tab bar view ui
  SickSangHae/View/TabBarView.swift
Labels: ⚒️ fix

#41 #44/change date
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/Global/Extensions/Number+Extension.swift
  SickSangHae/Info.plist
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ✨ feature

#55 #14/fix tab bar view UI
  SickSangHae/Application/Assets.xcassets/ChartActive.imageset/ChartActive.png
  SickSangHae/Application/Assets.xcassets/ChartActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/ChartDisActive.imageset/ChartDisActive.png
  SickSangHae/Application/Assets.xcassets/ChartDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryActive.imageset/HistoryActive.png
  SickSangHae/Application/Assets.xcassets/HistoryDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryDisActive.imageset/HistoryDisActive.png
  SickSangHae/Application/Assets.xcassets/RefActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/RefActive.imageset/RefActive.png
  SickSangHae/Application/Assets.xcassets/RefDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/RefDisActive.imageset/RefDisActive.png
  SickSangHae/Application/Assets.xcassets/SettingActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/SettingActive.imageset/SettingActive.png
  SickSangHae/Application/Assets.xcassets/SettingDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/SettingDisActive.imageset/SettingDisActive.png
  SickSangHae/View/TabBarView.swift
Labels: ⚒️ fix

#57 #14/implement main view
  SickSangHae/Application/Assets.xcassets/ChartActive.imageset/ChartActive.png
  SickSangHae/Application/Assets.xcassets/ChartActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/ChartDisActive.imageset/ChartDisActive.png
  SickSangHae/Application/Assets.xcassets/ChartDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryActive.imageset/HistoryActive.png
  SickSangHae/Application/Assets.xcassets/HistoryDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/HistoryDisActive.imageset/HistoryDisActive.png
  SickSangHae/Application/Assets.xcassets/RefActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/RefActive.imageset/RefActive.png
  SickSangHae/Application/Assets.xcassets/RefDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/RefDisActive.imageset/RefDisActive.png
  SickSangHae/Application/Assets.xcassets/SettingActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/SettingActive.imageset/SettingActive.png
  SickSangHae/Application/Assets.xcassets/SettingDisActive.imageset/Contents.json
  SickSangHae/Application/Assets.xcassets/SettingDisActive.imageset/SettingDisActive.png
  SickSangHae/View/MainView.swift
  SickSangHae/View/TabBarView.swift
Labels: ⚒️ fix

#58 feature: update ItemCheckView
  SickSangHae/View/ItemCheckView.swift
Labels: ✨ feature

#54 #44/text function
  SickSangHae/View/CameraView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/Reusable/TopAlertView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/TopAlertViewModel.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ✨ feature

#61 #44/add delete item block view
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ✨ feature

#62 feature: implement center alert view
  SickSangHae/View/Reusable/CenterAlertView.swift
Labels: ✨ feature

#68 #17/edit item detail view
  SickSangHae/View/EditItemDetailView.swift
  SickSangHae/View/ItemDetailView.swift
Labels: ✨ feature, ⚒️ fix

#65 #63/core data 연결하기
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature

#76 fix: found lost updateItemView data
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/UpdateItemView.swift
Labels: ⚒️ fix

#75 fix: ItemDetailView Extension Delete
  SickSangHae/View/EditItemDetailView.swift
Labels: ⚒️ fix

#73 #59/camera&ocr navigation
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/Fonts/Pretendard-Bold.otf
  SickSangHae/Application/Fonts/Pretendard-Medium.otf
  SickSangHae/Application/Fonts/Pretendard-Regular.otf
  SickSangHae/Application/Fonts/Pretendard-SemiBold.otf
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/Global/Extensions/Font+Extension.swift
  SickSangHae/Info.plist
  SickSangHae/View/CameraView.swift
  SickSangHae/View/GetScreenShotView.swift
  SickSangHae/View/ItemCheckView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/Reusable/OCRView.swift
  SickSangHae/View/Reusable/RegisterCompleteView.swift
  SickSangHae/View/Reusable/TopAlertView.swift
  SickSangHae/View/SupportView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/TopAlertViewModel.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ✨ feature

#77 #64/ChatGPTOpenAI Asynchronous
  .gitignore
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SickSangHae/Info.plist
  SickSangHae/View/ItemCheckView.swift
  SickSangHae/View/Reusable/OCRView.swift
  SickSangHae/ViewModel/OCRViewModel.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
  SickSangHaeTests/Info.plist
Labels: ✨ feature

#79 #44/final update item view
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ♻️ refactor

#80 #28/item detail view core data
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/EditIconDetailView.swift
  SickSangHae/View/EditItemDetailView.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/Reusable/SmallButtonView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature

#81 #44/update item view
  SickSangHae/View/CameraView.swift
  SickSangHae/View/Reusable/CenterAlertView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ✨ feature

#82 #28/coredata crud
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/EditIconDetailView.swift
  SickSangHae/View/EditItemDetailView.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/Reusable/SmallButtonView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature

#84 #64/ChatGPT OpenAI GPT prompt setting
  SickSangHae/View/ItemCheckView.swift
  SickSangHae/ViewModel/OCRViewModel.swift
Labels: ⚒️ fix

#86 #59/direct input flow
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/View/CameraView.swift
  SickSangHae/View/ItemCheckView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/OCRView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
Labels: ⚒️ fix, ♻️ refactor

#88 #87/chart view connect Core data
  SickSangHae/View/ChartView.swift
Labels: ✨ feature

#91 #59/separate direct input flow
  .gitignore
  SickSangHae.xcodeproj/project.pbxproj
  SickSangHae.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SickSangHae/Application/SickSangHaeApp.swift
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/Info.plist
  SickSangHae/View/CameraView.swift
  SickSangHae/View/DirectItemCheckView.swift
  SickSangHae/View/DirectUpdateItemView.swift
  SickSangHae/View/EditIconDetailView.swift
  SickSangHae/View/EditItemDetailView.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/View/ItemDetailView.swift
  SickSangHae/View/MainView.swift
  SickSangHae/View/OCRItemCheckView.swift
  SickSangHae/View/OCRUpdateItemView.swift
  SickSangHae/View/Reusable/BasicList.swift
  SickSangHae/View/Reusable/CenterAlertView.swift
  SickSangHae/View/Reusable/ItemBlockView.swift
  SickSangHae/View/Reusable/LongTermList.swift
  SickSangHae/View/Reusable/OCRView.swift
  SickSangHae/View/Reusable/SmallButtonView.swift
  SickSangHae/View/TabBarView.swift
  SickSangHae/View/UpdateItemView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
  SickSangHae/ViewModel/OCRViewModel.swift
  SickSangHae/ViewModel/UpdateItemViewModel.swift
  SickSangHaeTests/Info.plist
Labels: ♻️ refactor

#93 #12/history view date grouping
  SickSangHae/Global/Extensions/Date+Extension.swift
  SickSangHae/View/HistoryView.swift
  SickSangHae/ViewModel/CoreDataViewModel.swift
Labels: ✨ feature
